# Generated by Django 3.0.6 on 2020-05-23 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='checkuprequest',
            name='suitable_datetime',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='details',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
        migrations.DeleteModel(
            name='TravelRequest',
        ),
    ]
